# -*- coding: utf-8 -*-
"""Reto3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZUTJAegbSUBM4KWa7_4ec3EtOO4KYH4
"""

N = int(input())
contador = 0
disponible = False
precios = []
while contador < N:
  caracteristicas = input().split()
  pedalier = int(caracteristicas[0])
  bielas = int(caracteristicas[1])
  sillin = int(caracteristicas[2])
  manilar = int(caracteristicas[3])
  precio = int(caracteristicas[4])
  if not(pedalier>300 or pedalier<240) :
     if not(bielas>180 or bielas<160) :
       if not(sillin>275 or sillin<240) :
        if not(manilar>50 or manilar<0) :
          precios.append(precio) 
          disponible = True
  contador += 1
if disponible == False : 
   print("NO DISPONIBLE") 
else:
  for precio in precios:
    print(precio)